apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
spec:
  selector:
   matchLabels:
    app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          envFrom:
            - secretRef:
                name: pgadmin-email
            - secretRef:
                name: pgadmin-password
            - secretRef:
                name: pgadmin-port
          ports:
            - containerPort: 80
              name: pgadminport