apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  labels:
    app: pgadmin
spec:
  type: NodePort
  ports:
    - name: pgadmin
      port: 80
      nodePort: 30200
  selector:
    app: pgadmin
  